### ISSUE TITLE
Requesting the paper

### ISSUE THREAD

**Issue by Ramlinbird** [saichandra1/DoTNet#1]
S. Kosaraju, M. Masum, N. Tsaku, P. Patel, T. Bayramoglu, G. Modgil, and M. Kang†, "DoT-Net: Document Layout Classification Using Texture-based CNN", The 15th International Conference on Document Analysis and Recognition (ICDAR), 2019

Where can I get the source pdf of above paper? Thanks

**Comment by saichandra1** [comment]
Hello Ramlinbird,
I am sorry for late response, The conference was held in sept 25th, so we are expecting it will be in IEEE soon, if you need the other version of it, please send me your email to sai.kosaraju@unlv.edu

**Comment by Ramlinbird** [comment]
Thanks, I have saw your reply email~
